# Generated by Django 5.0.4 on 2024-05-10 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Interes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.facultad')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.CharField(max_length=300)),
                ('mensaje', models.TextField(default='')),
                ('foto', models.CharField(max_length=300, null=True)),
                ('video', models.CharField(max_length=300, null=True)),
                ('leido', models.BooleanField(default=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('usuario', models.CharField(choices=[('1', '1'), ('2', '2')], max_length=1)),
                ('matches', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.matches')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.CharField(max_length=300)),
                ('descripcion', models.CharField(max_length=250)),
                ('altura', models.CharField(max_length=45)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.carrera')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='matches',
            name='usuario1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_usuario1', to='miapp.perfil'),
        ),
        migrations.AddField(
            model_name='matches',
            name='usuario2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_usuario2', to='miapp.perfil'),
        ),
        migrations.CreateModel(
            name='Foto_extras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.CharField(max_length=300)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='PersonaInteres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.interes')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.perfil')),
            ],
        ),
    ]
