# Generated by Django 5.0.6 on 2024-06-30 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_perfil_banner_alter_perfil_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='altura',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='miapp.carrera'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='descripcion',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
