# Generated by Django 5.0.6 on 2024-06-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0003_alter_perfil_altura_alter_perfil_carrera_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='carrera',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='perfil',
            name='apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
