# Generated by Django 5.0.6 on 2024-06-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0004_remove_perfil_altura_remove_perfil_carrera_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='user',
            new_name='usuario',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='nombre',
        ),
        migrations.AddField(
            model_name='perfil',
            name='foto_banner',
            field=models.ImageField(blank=True, null=True, upload_to='banner/'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfil/'),
        ),
        migrations.AlterField(
            model_name='foto_extras',
            name='foto',
            field=models.ImageField(upload_to='extras/'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='mensajes/'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='video',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
