# Generated by Django 5.0.4 on 2024-07-02 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0006_rename_usuario_perfil_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultad',
            name='imagen',
            field=models.ImageField(null=True, upload_to='facultad/'),
        ),
    ]
