# Generated by Django 5.0.4 on 2024-07-02 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0007_facultad_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultad',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='facultad/'),
        ),
        migrations.AlterField(
            model_name='facultad',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
